In [4]:
import pandas as pd
d = {
    "id": "0001",
    "type": "donut",
    "name": "Cake",
    "ppu": 0.55,
    "batters":
        {
            "batter":
                [
                    { "id": "1001", "type": "Regular" },
                    { "id": "1002", "type": "Chocolate" },
                    { "id": "1003", "type": "Blueberry" },
                    { "id": "1004", "type": "Devil's Food" }
                ]
        },
    "topping":
        [
            { "id": "5001", "type": "None" },
            { "id": "5002", "type": "Glazed" },
            { "id": "5005", "type": "Sugar" },
            { "id": "5007", "type": "Powdered Sugar" },
            { "id": "5006", "type": "Chocolate with Sprinkles" },
            { "id": "5003", "type": "Chocolate" },
            { "id": "5004", "type": "Maple" }
        ]
}

In [8]:
def get_imp_data(d):
    df1 = pd.DataFrame(d['batters']['batter'])
    df1.columns = ['batter_id','batter_type']

    df2 = pd.DataFrame(d['topping'])
    df2.columns = ['topping_id','topping_type']
    df1['tmp'] = 1
    df2['tmp'] = 1
    df = df2.merge(df1,on=['tmp'])
    small_dict = {key:d[key] for key in d if key in ('id','type','name','ppu')}
    for k,v in small_dict.items():
        df[k] = v
        
    df =df.drop('tmp',axis=1)
    return df

In [9]:
get_imp_data(d)

,topping_id,topping_type,batter_id,batter_type,id,type,name,ppu
0,5001,None,1001,Regular,0001,donut,Cake,0.55
1,5001,None,1002,Chocolate,0001,donut,Cake,0.55
2,5001,None,1003,Blueberry,0001,donut,Cake,0.55
3,5001,None,1004,Devil's Food,0001,donut,Cake,0.55
4,5002,Glazed,1001,Regular,0001,donut,Cake,0.55
5,5002,Glazed,1002,Chocolate,0001,donut,Cake,0.55
6,5002,Glazed,1003,Blueberry,0001,donut,Cake,0.55
7,5002,Glazed,1004,Devil's Food,0001,donut,Cake,0.55
8,5005,Sugar,1001,Regular,0001,donut,Cake,0.55
9,5005,Sugar,1002,Chocolate,0001,donut,Cake,0.55
10,5005,Sugar,1003,Blueberry,0001,donut,Cake,0.55
11,5005,Sugar,1004,Devil's Food,0001,donut,Cake,0.55
12,5007,Powdered Sugar,1001,Regular,0001,donut,Cake,0.55
13,5007,Powdered Sugar,1002,Chocolate,0001,donut,Cake,0.55
14,5007,Powdered Sugar,1003,Blueberry,0001,donut,Cake,0.55
15,5007,Powdered Sugar,1004,Devil's Food,0001,donut,Cake,0.55
16,5006,Chocolate with Sprinkles,1001,Regular,0001,donut,Cake,0.55
17,5006,Chocolate with Sprinkles,1002,Chocolate,0001,donut,Cake,0.55
18,5006,Chocolate with Sprinkles,1003,Blueberry,0001,donut,Cake,0.55
19,5006,Chocolate with Sprinkles,1004,Devil's Food,0001,donut,Cake,0.55
20,5003,Chocolate,1001,Regular,0001,donut,Cake,0.55
21,5003,Chocolate,1002,Chocolate,0001,donut,Cake,0.55
22,5003,Chocolate,1003,Blueberry,0001,donut,Cake,0.55
23,5003,Chocolate,1004,Devil's Food,0001,donut,Cake,0.55
24,5004,Maple,1001,Regular,0001,donut,Cake,0.55
25,5004,Maple,1002,Chocolate,0001,donut,Cake,0.55
26,5004,Maple,1003,Blueberry,0001,donut,Cake,0.55
27,5004,Maple,1004,Devil's Food,0001,donut,Cake,0.55

In [23]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
vec1 = np.array([[1,1,0,1,1]])
vec2 = np.array([[2,1,0,-1,1]])
#print(cosine_similarity([vec1, vec2]))
val = cosine_similarity(vec1, vec2)

In [25]:
val[0][0]

0.5669467095138407

In [20]:
vec1.shape

(1, 5)