In [1]:
# tmdb_5000_movies
# tmdb_5000_credits

In [ ]:
# jupyter notebook

In [8]:
import pandas as pd

In [10]:
df_movies = pd.read_csv(r"D:\OneDrive - NITT\Custom_Download\tmdb_5000_movies.csv")
df_credits = pd.read_csv(r"D:\OneDrive - NITT\Custom_Download\tmdb_5000_credits.csv")

In [11]:
df_movies

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",1992-09-04,2040920,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],[],2011-12-26,0,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-10-13,0,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6
4801,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-05-03,0,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7
4802,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-08-05,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16

In [12]:
df_credits

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...
4798,9367,El Mariachi,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4799,72766,Newlyweds,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4800,231617,"Signed, Sealed, Delivered","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4801,126186,Shanghai Calling,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4802,25975,My Date with Drew,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [19]:
df_movies[:2].T

,0,1
budget,237000000,300000000
genres,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""..."
homepage,http://www.avatarmovie.com/,http://disney.go.com/disneypictures/pirates/
id,19995,285
keywords,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na..."
original_language,en,en
original_title,Avatar,Pirates of the Caribbean: At World's End
overview,"In the 22nd century, a paraplegic Marine is di...","Captain Barbossa, long believed to be dead, ha..."
popularity,150.437577,139.082615
production_companies,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""..."
production_countries,"[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_3166_1"": ""US"", ""name"": ""United States o..."
release_date,2009-12-10,2007-05-19
revenue,2787965087,961000000
runtime,162.0,169.0
spoken_languages,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...","[{""iso_639_1"": ""en"", ""name"": ""English""}]"
status,Released,Released
tagline,Enter the World of Pandora.,"At the end of the world, the adventure begins."
title,Avatar,Pirates of the Caribbean: At World's End
vote_average,7.2,6.9
vote_count,11800,4500

In [20]:
#Todo
# 0) go through pandas
# 
# 2) use the following columns:- revenue,runtime,vote_average,vote_count,original_language,budget,popularity

In [26]:
df_movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [28]:
data = df_movies[['revenue','runtime','vote_average','vote_count','original_language','budget','popularity']]

In [29]:
data

,revenue,runtime,vote_average,vote_count,original_language,budget,popularity
0,2787965087,162.0,7.2,11800,en,237000000,150.437577
1,961000000,169.0,6.9,4500,en,300000000,139.082615
2,880674609,148.0,6.3,4466,en,245000000,107.376788
3,1084939099,165.0,7.6,9106,en,250000000,112.312950
4,284139100,132.0,6.1,2124,en,260000000,43.926995
...,...,...,...,...,...,...,...
4798,2040920,81.0,6.6,238,es,220000,14.269792
4799,0,85.0,5.9,5,en,9000,0.642552
4800,0,120.0,7.0,6,en,0,1.444476
4801,0,98.0,5.7,7,en,0,0.857008
4802,0,90.0,6.3,16,en,0,1.929883

In [30]:
# modify text into numeric i.e categorical to numeric column

In [33]:
data['original_language'].unique()

array(['en', 'ja', 'fr', 'zh', 'es', 'de', 'hi', 'ru', 'ko', 'te', 'cn',
       'it', 'nl', 'ta', 'sv', 'th', 'da', 'xx', 'hu', 'cs', 'pt', 'is',
       'tr', 'nb', 'af', 'pl', 'he', 'ar', 'vi', 'ky', 'id', 'ro', 'fa',
       'no', 'sl', 'ps', 'el'], dtype=object)

In [34]:
data = pd.get_dummies(data)

In [35]:
data

,revenue,runtime,vote_average,vote_count,budget,popularity,original_language_af,original_language_ar,original_language_cn,original_language_cs,...,original_language_ru,original_language_sl,original_language_sv,original_language_ta,original_language_te,original_language_th,original_language_tr,original_language_vi,original_language_xx,original_language_zh
0,2787965087,162.0,7.2,11800,237000000,150.437577,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,961000000,169.0,6.9,4500,300000000,139.082615,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,880674609,148.0,6.3,4466,245000000,107.376788,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1084939099,165.0,7.6,9106,250000000,112.312950,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,284139100,132.0,6.1,2124,260000000,43.926995,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,2040920,81.0,6.6,238,220000,14.269792,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4799,0,85.0,5.9,5,9000,0.642552,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4800,0,120.0,7.0,6,0,1.444476,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4801,0,98.0,5.7,7,0,0.857008,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4802,0,90.0,6.3,16,0,1.929883,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [36]:
data.dtypes

revenue                   int64
runtime                 float64
vote_average            float64
vote_count                int64
budget                    int64
popularity              float64
original_language_af      uint8
original_language_ar      uint8
original_language_cn      uint8
original_language_cs      uint8
original_language_da      uint8
original_language_de      uint8
original_language_el      uint8
original_language_en      uint8
original_language_es      uint8
original_language_fa      uint8
original_language_fr      uint8
original_language_he      uint8
original_language_hi      uint8
original_language_hu      uint8
original_language_id      uint8
original_language_is      uint8
original_language_it      uint8
original_language_ja      uint8
original_language_ko      uint8
original_language_ky      uint8
original_language_nb      uint8
original_language_nl      uint8
original_language_no      uint8
original_language_pl      uint8
original_language_ps      uint8
original_language_pt      uint8
original_language_ro      uint8
original_language_ru      uint8
original_language_sl      uint8
original_language_sv      uint8
original_language_ta      uint8
original_language_te      uint8
original_language_th      uint8
original_language_tr      uint8
original_language_vi      uint8
original_language_xx      uint8
original_language_zh      uint8
dtype: object

In [51]:
data.dropna(inplace=True)

In [52]:
X = data.drop('popularity',axis=1)

In [53]:
y = data['popularity']

In [54]:
from sklearn.model_selection import train_test_split

In [55]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [68]:
X_train

,revenue,runtime,vote_average,vote_count,budget,original_language_af,original_language_ar,original_language_cn,original_language_cs,original_language_da,...,original_language_ru,original_language_sl,original_language_sv,original_language_ta,original_language_te,original_language_th,original_language_tr,original_language_vi,original_language_xx,original_language_zh
2852,22939027,94.0,5.6,364,12000000,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3263,74952305,92.0,6.7,2210,8000000,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4579,5028948,91.0,7.8,1708,400000,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1774,6673422,104.0,5.2,127,25000000,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1957,34670720,119.0,7.0,257,14000000,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4428,0,87.0,5.7,92,950000,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
466,123729176,96.0,5.8,631,80000000,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3093,0,104.0,6.8,37,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3773,1919197,96.0,6.1,67,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
860,89519773,119.0,6.9,573,55000000,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [56]:
# Linear regression

from sklearn.linear_model import LinearRegression

In [57]:
reg_model = LinearRegression()

In [58]:
reg_model.fit(X_train,y_train)

LinearRegression()

In [59]:
y_pred = reg_model.predict(X_test)

In [67]:
y_pred # predicted popularity

array([ 1.34490933e+01,  5.94656478e+00,  1.03318181e+01,  2.41620216e+01,
        1.24173185e+02,  3.30523263e+01,  1.10539173e+01,  4.49585245e+01,
        8.61893701e+00,  2.60762346e+01,  9.89931984e+00,  1.29696800e+00,
        7.73163820e+00,  2.89125501e+01,  4.18039454e+01,  2.07528724e+01,
        9.20729995e+00,  5.33186569e+01,  1.70325093e+01,  9.93424284e+00,
        1.94420948e+01,  1.53676097e+01,  6.88935116e+00,  6.23703801e+01,
        2.42507361e+01,  1.01798960e+01,  7.11598019e+00,  1.11505272e+01,
        8.22939052e+00,  3.01962097e+01,  6.68894897e+00,  8.19076947e+00,
        1.02160004e+02,  1.35307892e+01,  7.94810914e+00,  8.45807538e+00,
        4.03413386e+01,  3.84363098e+01,  2.01147340e+01,  1.13879329e+01,
        8.33229295e+01,  7.24111079e+01,  6.39151619e+00,  1.46037638e+02,
        9.55097701e+00,  3.93421332e+01,  1.02595997e+01,  8.06644629e+00,
        3.50546410e+01,  2.30779509e+01,  1.58062490e+01,  1.98987621e+01,
        8.64596786e+00,  1.64192980e+01,  1.27187384e+01,  5.84632794e+00,
        2.23991019e+01,  2.50627861e+01,  6.88765240e+00,  1.39739233e+01,
        6.46110533e+00,  3.61722530e+01,  7.92389465e+00,  2.32554198e+01,
        3.08588573e+01,  3.87263436e+01,  8.79192775e+00,  1.73615681e+01,
        6.91919208e+00,  4.87417075e+00,  5.40988550e+00,  7.90514053e+00,
        2.49904632e+01,  4.25515867e+01,  6.40758679e+01,  2.90476716e+01,
        3.84091615e+00,  2.34322692e+01,  7.16594213e+00,  2.52818480e+01,
        7.73005810e+00,  2.33013860e+00,  2.41661731e+01,  1.41768469e+01,
        6.66463807e+00,  1.51514002e+01,  1.12595033e+01,  3.46269076e+01,
        1.64209156e+01,  1.91649538e+01,  1.29499131e+01,  1.03679771e+01,
        2.06416144e+01,  2.46422541e+02,  1.01301366e+01,  1.48322490e+02,
        1.39541312e+01,  2.18676273e+01,  8.89839371e+00,  1.20791694e+01,
        1.43701696e+01,  3.84902350e+01,  1.32345582e+01,  4.12060985e+01,
        2.34938738e+01,  1.12471783e+01,  4.44608151e+00,  9.45873959e+01,
        7.32098500e+00,  7.76774215e+00,  9.99408369e+00,  6.16090123e+00,
        7.28386596e+00,  1.35739325e+01,  2.86887675e+01,  1.71406616e+01,
        1.25219535e+01,  1.15342852e+01,  1.35087366e+01,  3.43006537e+01,
        6.68691058e+00,  1.79824487e+01,  2.16280957e+01,  9.19237911e+00,
        9.82116106e+00,  6.79780367e+00,  6.07944072e+00,  2.00390512e+02,
        3.90031978e+01,  8.39192396e+00,  1.34750543e+01,  8.76080837e+00,
        5.64530746e+00,  3.54030151e+01,  8.74800807e+00,  2.33045381e+01,
        5.85881561e+00,  3.23165754e+01,  1.04475699e+01, -3.19483432e-01,
        1.30624563e+01,  1.35159882e+01,  1.73584487e+01,  9.30885717e+00,
        1.14531737e+01,  4.07653148e+01,  9.10634252e+00,  3.77533019e+01,
        2.56593746e+01,  5.75266531e+01,  7.44785737e+00,  1.39604932e+01,
        5.22008512e+00,  4.77744545e+00,  9.01792330e+00,  1.05629158e+01,
        2.78545859e+01,  1.91672043e+02,  1.61693870e+01,  5.43092476e+01,
        8.16464823e+00,  1.69980968e+01,  8.78906590e+00,  6.45808485e+00,
        1.00520566e+01,  1.12999648e+01,  2.24626436e+01,  2.14894316e+01,
        1.43382575e+01,  7.12209469e+01,  4.71038333e+00,  8.03653230e+00,
        1.89781512e+01,  7.79618625e+00,  9.50887586e+00,  4.10630182e+01,
        2.91977538e+01,  4.83549900e+01,  8.57884741e+00,  8.54745980e+00,
        2.04310511e+01,  1.65423298e+01,  7.08954172e+00,  6.71584927e+00,
        1.57831799e+01,  6.69813572e+01,  7.77582535e+00,  1.13433879e+01,
        1.36614217e+01,  1.06615768e+01,  2.00799547e+01,  3.81402120e+01,
        6.44320003e+01,  1.47335563e+01,  1.57849598e+01,  1.62719423e+02,
        1.51603199e+01,  6.39244408e+00,  1.53480279e+01,  1.50579670e+01,
        2.89322818e+01,  8.75862827e+00,  1.03087594e+01,  1.19631293e+02,
        9.48090176e+00,  6.27079396e+00,  2.12953645e+01,  1.43826667e+01,
        1.00344608e+01,  8.03434987e+00,  7.59499457e+00,  1.59230906e+01,
        4.88420599e+00,  1.16319465e+01,  1.29530107e+01,  7.05161402e+01,
        5.58333416e+01,  6.90476436e+00,  9.72207452e+00,  1.47415743e+01,
        8.44879223e+00,  1.41157218e+01,  4.51294015e+01,  1.31938658e+00,
        3.44136581e+01,  8.10050644e+00,  1.20351818e+01,  4.97692142e+01,
        1.31010936e+01,  1.03540522e+01,  9.50270074e+00,  3.29289831e+01,
        1.09770327e+01,  7.60097057e+01,  2.12850155e+01,  6.69167441e+01,
        5.34755421e+01,  2.35157996e+01,  1.17123566e+01,  6.81926527e+00,
        9.56000230e+00,  2.24954759e+01,  6.55905040e+00,  2.14875452e+01,
        9.23596535e+01,  8.31202347e+00,  9.84542056e+00,  1.28912951e+01,
        2.06498722e+01,  2.10900125e-01,  1.23877872e+02,  2.56626682e+01,
        1.17392101e+01,  1.11223845e+01,  1.77460034e+01,  6.95728700e+00,
        9.11078364e+00,  1.17388858e+01,  2.37999801e+01,  8.82173695e+00,
        8.46415425e+00,  6.72029355e+00,  1.00125777e+01,  6.98363502e+01,
        1.57866371e+01,  1.54256521e+00,  3.43155850e+01,  1.23036939e+01,
        6.65049537e+00,  4.80424337e+00,  4.02062984e+01,  3.14180743e+01,
        9.46294870e+00,  1.59918350e+01,  8.48217688e+00,  9.03023449e+00,
        1.12911824e+01,  2.26239125e+01,  1.52993524e+01,  2.14021161e+01,
        6.93803434e+00,  5.70446154e+00,  9.28208057e+00,  1.67778006e+01,
        9.25526759e+00,  6.36794712e+00,  2.38145933e+00,  6.11179767e+00,
        1.03204207e+01,  7.38867958e+00,  2.25665971e+01,  4.64642042e+01,
        1.31236363e+01,  9.02634980e+00,  1.64845235e+01,  5.53210444e+00,
        6.19022096e+01,  1.52652502e+01,  2.55663892e+01,  9.06423128e+00,
        6.59675337e+00,  1.22748949e+00,  1.08540494e+01,  7.73789147e+00,
        3.78679207e+01,  3.79329713e+01,  7.20681163e+00,  9.49404738e+00,
        1.29798291e+01,  2.24562083e+01,  4.26543465e+01,  2.30584108e+01,
        8.09115048e+00,  6.47065093e+01,  2.92357299e+01,  6.46634191e+00,
        1.27594564e+01,  2.50636604e+01,  3.33586885e+00,  1.29645721e+01,
        4.97300375e+01,  1.17067212e+01,  5.33493607e+00,  2.73696269e+01,
        8.48718229e+01,  1.10132106e+01,  9.78825389e+00,  2.13830446e+01,
        1.11016275e+01,  4.11476692e+01,  1.69762770e+01,  8.50597882e+00,
        8.20108685e+00,  1.62004719e+01,  5.82955511e+01,  1.88799833e+01,
        7.66593755e+00,  2.21895797e+01,  1.80602017e+01,  4.98573630e+01,
        8.18468603e+00,  3.31994387e+01,  3.47506079e+01,  2.11277757e+01,
        8.18416483e+01,  2.00285518e+01,  7.95091704e+00,  1.32510242e+01,
        1.82756398e+01,  2.55656537e+01,  2.01566373e+01,  9.21852089e+00,
        1.67346858e+02,  5.71340035e+00,  2.45863615e+01,  1.32666596e+01,
        1.77759212e+01,  2.96347827e+01,  8.82232624e+00,  2.02203479e+01,
        2.00928466e+01,  1.30397041e+01,  2.19191434e+01,  9.74909889e+00,
        7.46300640e+00,  3.15476925e+01,  1.73672563e+01,  9.73669122e+00,
        8.01336364e+00,  8.44508157e+00,  9.44638909e+01,  8.44707931e+00,
        8.99427808e+00,  6.68665588e+00,  9.84629482e+00,  1.27514637e+01,
        2.74014677e+01,  3.54280713e+01,  1.54066136e+01,  1.38994109e+01,
        1.53111887e+01,  7.30034651e+00,  6.31536065e+01,  1.99757639e+01,
        2.49383328e+01,  1.33862847e+01,  9.50811917e+00,  9.07041435e+00,
        3.28919267e+01,  2.03997780e+01,  1.08903611e+01,  8.35618456e+00,
        1.42921061e+01,  8.50522153e+00,  3.20222564e+01,  2.54978176e+01,
        9.56713592e+01,  9.50153192e+00,  3.81029621e+00,  8.14109052e+00,
        3.41057249e+01,  7.58239056e+00,  5.87442535e+00,  9.99636045e+01,
        1.89591970e+01,  2.88537934e+01,  6.43823977e+01,  2.53072555e+01,
        6.73109402e+00,  1.71178332e+01,  7.40947489e+00,  5.08960708e+01,
        4.34056115e+00,  8.79512812e+00,  6.90639841e+00,  1.20195945e+01,
        1.98997321e+01,  2.46478308e+01,  4.83184043e+00,  7.93818794e+00,
        2.64266484e+01,  7.79354349e+00,  8.66338305e+00,  1.33338349e+01,
        7.68627802e+00,  7.69626678e+00,  8.14638878e+00,  2.06478151e+01,
        5.99960030e+00,  8.19218558e+00,  3.51847220e+01,  4.79335681e+00,
        2.63307534e+01,  9.43227049e+00,  1.04494082e+02,  1.00616280e+01,
        1.24252187e+01,  1.20604786e+01,  8.24821985e+00,  3.79934555e+01,
        1.22142865e+01,  2.10502572e+01,  4.49016642e+01,  1.21094128e+01,
        1.92912732e+01,  3.49854439e+00,  8.10212135e+00,  1.03502588e+01,
        6.19445456e+00,  1.98694759e+01,  5.71645343e+01,  1.21749747e+02,
        5.65343382e+00,  1.13203972e+01,  4.07546503e+01,  4.27595833e+00,
        9.24298542e+00,  2.63102680e+01,  2.06051433e+01,  3.33769263e+01,
        4.12843226e+01,  1.99813642e+01,  1.57837224e+01,  1.13018936e+01,
        2.18931503e+01,  9.03917492e+00,  8.75532482e+00,  7.86474734e+00,
        6.51039684e+01,  4.51805784e+01,  1.27055739e+01,  2.46153606e+00,
        1.81401003e+01,  8.03194534e+00,  8.73990168e+00,  4.98705830e+00,
        9.15327069e+00,  2.19731341e+01,  5.36045751e+00,  2.81422966e+01,
        1.00427378e+01,  4.94495899e+00,  3.89944654e+00,  1.12434012e+01,
        7.84106020e+00,  6.37909065e+01,  5.58462215e+01,  9.11300204e+00,
        1.36059782e+01,  2.45164723e+01,  6.82272429e+00,  4.64492780e+01,
        6.46266475e+00,  7.60499544e+00,  9.84296148e+00,  9.83524400e+00,
        1.80544758e+01,  7.51945475e+01,  1.89784727e+01,  8.74668368e+00,
        2.23762098e+01,  4.46990813e+01,  1.20541290e+01,  7.20329868e+00,
        1.75449680e+01,  1.85751220e+01,  6.49637659e+00,  3.35325858e+01,
        8.45319380e+00,  9.69051262e+00,  7.62481460e+00,  8.72578432e+00,
        1.04934351e+02,  3.69592795e+01,  4.86067182e+01,  1.17498421e+01,
        1.42685374e+00,  7.28651574e+00,  2.86227692e+01,  1.87522543e+01,
        7.46163832e+00,  3.42921166e+01,  1.14036502e+01,  6.30326710e+01,
        9.51338554e+00,  1.09714044e+01,  1.05915715e+01,  1.41382568e+01,
        3.25401087e+01,  8.57018317e+00,  5.32073720e+01,  5.17739614e+01,
        2.23239166e+01,  8.02755528e+00,  3.03689686e+01,  8.04587701e+01,
        9.81930503e+00,  1.14949920e+01,  1.08754227e+01,  8.67434156e+00,
        1.05526901e+01,  8.86702368e+01,  1.25374580e+00,  1.11192398e+01,
        2.59325291e+01,  2.35451861e+01,  2.37996518e+01,  1.79851386e+01,
        8.05618577e+00,  8.95044145e+01,  1.08265970e+01,  2.73686682e+01,
        2.62753117e+01,  6.64692091e+00,  1.00278906e+01,  9.09802297e+00,
        1.12760615e+01,  1.11362334e+02,  8.28781759e+00,  3.16863750e+01,
        1.87857581e+01,  5.50285610e+00,  4.88687146e+00,  2.24784774e+01,
        2.64960843e+01,  1.09030456e+01,  1.16614578e+02,  5.64995702e+00,
        7.93916898e+00,  7.44656436e+00,  5.97104381e+00,  1.16362392e+01,
        8.97466036e+00,  1.18109606e+01,  9.54645023e+00,  8.17645925e+00,
       -5.45587779e-01,  2.77257684e+01,  9.68670811e+00,  1.35742746e+02,
        3.49135973e+01,  1.27764162e+01,  1.37887033e+01,  8.85429127e+00,
        9.92629448e+00,  4.05223957e+01,  1.78356783e+01,  1.10059346e+01,
        1.00897902e+01,  2.19090131e+01,  1.21047896e+01,  8.00457715e+00,
        8.07990861e+00,  8.91061152e+00,  1.52214776e+01,  9.33991245e+00,
        2.08708418e+01,  4.60568408e+01,  8.59168672e+00,  2.58332156e+01,
        7.79322429e+00,  2.06433986e+01,  4.57960271e+01,  1.55828886e+01,
        7.86499566e+00,  1.76796225e+01,  1.10608297e+01,  5.66147965e+01,
        1.72886086e+01,  3.11210127e+01,  6.58889900e+00,  1.21415012e+02,
        1.24172520e+01,  8.49311943e+00,  7.28703460e+00,  7.54644479e+00,
        6.97695141e+00,  1.45950615e+01,  9.94050923e+00,  1.63703676e+01,
        9.27026112e+00,  1.44807103e+01,  3.42879527e+01,  1.09620794e+00,
        8.13123948e+00,  1.42214425e+01,  1.08097995e+01,  3.75032315e+01,
        1.17414802e+01,  7.75294421e+00,  1.48190710e+01,  2.28781984e+01,
        8.75823564e+00,  7.87609670e+00,  1.54505541e+01,  3.79341076e+00,
        1.24729684e+01,  1.04096955e+01,  2.02337963e+01,  1.94256948e+01,
        9.42935059e+00,  2.17001343e+01,  2.27854308e+01,  9.37989052e+01,
        1.28663877e+01,  2.12456927e+01,  1.28232825e+01,  1.52213433e+01,
        2.51998233e+01,  3.14225490e+01,  8.14371122e+00,  1.25487715e+01,
        2.00412453e+01,  1.30445949e+01,  4.99737515e+00,  1.01560946e+01,
        2.12824959e+01,  1.14655447e+02,  8.51553989e+00,  1.22715645e+01,
        1.07160176e+01,  7.71836518e+00,  2.05769595e+01,  1.10121529e+01,
        3.93253186e+01,  1.01191816e+01,  9.23456868e+00,  9.91878648e+00,
        2.13971068e+01,  6.49596578e+00,  6.54883444e+00,  1.11814134e+01,
        2.35772406e+01,  3.75353779e+01,  8.00768172e+01,  8.99533350e+00,
        7.12390442e+00,  2.77557889e+01,  1.01702828e+01,  1.14883947e+01,
        9.21767153e+00,  1.02283300e+01,  1.52919132e+01,  1.20704333e+01,
        2.63772049e+01,  1.05401379e+01,  1.41489084e+01,  1.83547571e+01,
        1.90809793e+01,  7.84755137e+00,  6.83079709e+00,  9.35865475e+00,
        8.93244357e+00,  1.01500322e+01,  1.14989365e+01,  1.44263858e+01,
        1.72265327e+01,  5.40998277e+00,  1.69638972e+01,  6.19880218e+00,
        6.45704689e+00,  2.56525723e+01,  1.07892631e+01,  6.14301358e+00,
        1.22112873e+02,  1.04413134e+01,  1.21378045e+01,  7.73578632e+00,
        1.71096004e+01,  1.20469068e+01,  5.61860013e+00,  4.05897740e+01,
        5.07597856e+01,  5.20330832e+00,  1.46524700e+01,  1.06460052e+01,
        2.69286293e+01,  2.09160570e+01,  2.34442302e+01,  3.97683736e+01,
        1.79862324e+02,  3.84685190e+01,  7.55210169e+00,  2.74790215e+02,
        1.17354517e+01,  5.37739992e+01,  1.38314929e+01,  2.29443031e+01,
        1.46549166e+01,  6.42557070e+00,  8.15158231e+00,  7.49249510e+00,
        1.59802360e+01,  9.09455912e+00,  1.25137102e+01,  8.85879053e+00,
        9.99390871e+00,  1.31642810e+01,  2.28082885e+01,  2.38076911e+01,
        1.61682569e+01,  5.28336235e+01,  9.54630149e+00,  2.54126667e+01,
        1.06795366e+01,  7.01643638e+00,  1.56591459e+01,  7.39366843e+01,
        9.30337840e+00,  8.15967057e+00,  3.07156395e+01,  1.15809622e+01,
        9.01986015e+00,  1.70190049e+01,  6.33279558e+01,  8.52622154e+00,
        8.18279815e+00,  1.34680623e+01,  8.02999058e+00,  1.26581738e+02,
        6.96631179e+00,  1.12413402e+01,  1.72193716e+01,  1.17659134e+01,
        3.08589567e+01,  3.70576717e+01,  7.43755879e+00,  2.24488981e+01,
        3.08299486e+01,  7.93500818e+00,  7.89843471e+00,  8.89554613e+00,
        4.54736269e+00,  9.88862804e+00,  7.59135920e+00,  1.19484558e+01,
        1.29304164e+01,  9.91887712e+00,  1.45551289e+01,  1.30625842e+00,
        7.11495383e+01,  7.20654887e+00,  7.40871659e+01,  1.15109682e+01,
        2.38790093e+01,  1.78465511e+01,  1.30319759e+02,  6.01528283e+00,
        9.59307210e+00,  9.87158793e+00,  8.70179590e+00,  8.98554357e+00,
        1.27403809e+01,  1.50289881e+01,  5.55811471e+00,  8.03246751e+00,
        1.73388606e+01,  6.64478127e+00,  6.93873997e+00,  9.36659546e+00,
        1.37047692e+01,  2.34482425e+01,  1.62396855e+01,  9.90233797e+00,
        1.21088332e+01,  7.24063647e+00,  3.34940305e+01,  2.32221539e+01,
        3.64451836e+01,  2.15965947e+01,  7.01090649e+01,  1.03418946e+01,
        2.05985441e+01,  7.94717138e+00,  1.86831280e+01,  2.07751487e+01,
        2.19920064e+02,  7.09069144e+00,  8.38119021e+00,  2.64759289e+01,
        5.36776600e+00,  8.75302044e+00,  7.32566821e+01,  2.04044007e+01,
        3.22114829e+01,  2.20944606e+01,  9.16962682e+00,  1.26459469e+01,
        7.35261110e+00,  1.18402695e+01,  4.84809224e+01,  2.02454863e+01,
        5.00010192e+00,  9.88819117e+00,  1.41252987e+00,  1.69357417e+01,
        1.25944555e+01,  5.40750650e+00,  3.04569383e+01,  9.07967792e+00,
        1.02428098e+01,  9.13812771e+00,  7.27093136e+00,  1.21300900e+01,
        8.10077658e+00,  1.90896861e+02,  1.24958042e+01,  3.91830601e+01,
        8.74786156e+00,  1.06092230e+01,  1.83319438e+01,  9.79166671e+00,
        1.28993664e+01,  9.23600918e+00,  8.07064971e+00,  1.67384676e+00,
        1.43769607e+01,  1.03758931e+01,  1.68600194e+01,  7.57807501e+00,
        1.44297219e+01,  3.31305156e+01,  9.03414957e+00,  4.44761917e+01,
        8.64251364e+01,  3.16354172e+01,  7.73565125e+00,  1.50087506e+01,
        7.46460474e+00,  1.08307979e+00,  3.05788589e+01,  1.65374568e+02,
        1.65335021e+01,  1.93151260e+01,  1.56603632e+01,  1.36306569e+01,
        1.81725440e+01,  8.33720861e+00,  2.51417746e+01,  8.56405968e+00,
        2.58349885e+01,  9.53175282e+00,  6.90511584e+00,  1.21222375e+01,
        4.06829377e+01,  9.29645438e+00,  3.72235265e+01,  1.54370834e+01,
        2.74480984e+01,  1.43190017e+01,  8.59093579e+00,  8.70191303e+00,
        6.63334124e+00,  3.77490134e+01,  7.99667618e+01,  6.12975430e+00,
        7.34557770e+00,  1.22100796e+01,  1.44472677e+01,  1.66932713e+01,
        1.31352905e+01,  1.15362934e+01,  7.21200116e+00,  1.20322483e+01,
        5.20094876e+01,  7.56826341e+00,  1.78444641e+01,  9.39739207e+00,
        4.77568982e+00,  6.92627583e+01,  1.90979280e+01,  2.62728718e+01,
        4.06799564e+01,  7.22652623e+00,  2.10924192e+01,  9.30865193e+00,
        1.55700411e+01,  1.00365771e+01,  5.24709814e+01,  9.05116037e+00,
        8.50494788e+00,  9.47918280e+01,  2.32811978e+01,  8.36177873e+00,
        1.30324172e+01,  1.87154559e+01,  1.52487822e+02,  1.37316263e+01,
        7.66184931e+00,  5.86178032e+00,  4.94622857e+01,  2.43011160e+01,
        1.88231229e+01,  2.08230862e+01,  8.47675582e+01,  9.50155437e+01,
        1.06342426e+01,  1.85315712e+01,  8.33977135e+00,  8.32723710e+00,
        1.08627838e+02,  3.24761261e+01,  8.51867026e+00,  1.94219655e+01,
        2.44427648e+01,  8.21248107e+00,  1.04377335e+01,  9.91239234e+01,
        4.19397500e+00,  1.67928053e+01,  1.08837274e+01,  9.60369064e+00,
        1.78421647e+01,  1.04083432e+01,  1.22105846e+01,  8.01027709e+00,
        3.34253474e+01,  5.13870234e+01,  8.92450386e+00,  2.00980913e+01,
        5.99026500e+01])

In [61]:
y_test # actual test popularity

596     13.267631
4509     0.001586
3050     9.525626
2958    32.943848
8       98.885637
          ...
198     39.448066
2422    32.746486
1485     7.339908
402     24.107835
2760    66.113340
Name: popularity, Length: 961, dtype: float64

In [69]:
pd.DataFrame({'y_actual':y_test,'y_pred':y_pred})

       y_actual      y_pred
596   13.267631   13.449093
4509   0.001586    5.946565
3050   9.525626   10.331818
2958  32.943848   24.162022
8     98.885637  124.173185
...         ...         ...
198   39.448066   33.425347
2422  32.746486   51.387023
1485   7.339908    8.924504
402   24.107835   20.098091
2760  66.113340   59.902650

[961 rows x 2 columns]

In [62]:
from sklearn.metrics import mean_squared_error

In [66]:
mse = mean_squared_error(y_test,y_pred)  #True returns MSE value, if False returns RMSE value.
mse

500.2558481379296

In [65]:
rmse = mean_squared_error(y_test, y_pred, squared=False)
rmse

22.36639998162265